### PR TITLE
Ticketless support + Ticketless multicontent support + Automation Script files

### PR DESCRIPTION
**Pull request by ElektroStudios**
### Part 1: Introducing Experimental Support for Ticketless - Single or Multicontent - Dumps 
------

As someone who isn't a Python programmer I’ve tried to make minimal changes to the source code to enable users to compress/decompress ticketless dumps that include only the base game. These changes should also support lossless compression and decompression of ticketless multicontent dumps. While I found that some non-ticketless multicontent dumps can also be compressed/decompressed, in general can't be compressed (due existing limitations of nsz I suppose) so I only recommend processing a ticketless multicontent dump.

Important mentions:

 - Hash verification in `__decompressContainer` method was altered to skip ticketless ncas, avoiding to cause any exception.
 - Title key extraction in `extractTitlekeys` method was altered to skip ticketless files, avoiding to cause any exceptions. (in other words, using `--titlekeys` parameter will have no effect when processing a ticketless dump.)

So theoretically these changes were applied in a way that ensures not to affect the normal behavior of nsz when processing a non-ticketless dump.

PS: You may want to review and decide the location for the `isTicketless` global variable that I've defined in the `Ticket.py` file.

### Part 2: Introducing Automation Scripts
------

I've created a folder which includes various automation script files written in Batch-Script.

Also included a brief comment in README.md under '#few-usage-examples' section pointing to the automation scripts folder.

Screenshot:

WinSnap 01

### CODE REVIEW

**Comment by ElektroStudios** [comment]
I've committed a "late fix" for which I've added two conditionals in `__init__.py` file to avoid deleting a generated .nsz file from a ticketless dump when the program fails to verify its hash.

This only affects when processing ticketless dumps, and I've added this change because it gives false positives for many ticketless dumps...

The following image demonstrates there is no byte difference between (right side) a source ticketless nsp file and (left side) the same nsp file after being compressed and decompressed using nsz.

WinSnap 01

**Comment by nicoboss** [comment]
Thank you so much for your awesome contribution. With support for ticketless and multi-content dumps you implemented a highly anticipated feature.

Thanks a lot for ensuring bit-identical reconstruction is NSP reconstruction works even for ticketless and multi-content NSZ files.

I reviewed your code and am satisfied with it. It passed all the CI/CD testes and manual tests confirming it is unlikely to break anything.

I plan on including your changes in the upcoming NSZ v4.7.0 release which will is scheduled to happen within the next 2 weeks.

There are a two concerns/questions I have:
- NSZ supports processing multiple files simultaneously. By default, 4 files are processed simultaneously. global variables in python are static meaning every instance of Ticket will share the same global isTicketless state. This should cause issues if the user mixes non-ticketless with ticketless files as they will keep overwriting each other’s isTicketless state. The only reason this works is probably because global variables are not shared between multiple processes and NSZ is using multiprocessing to process multiple files at once.
- Why do non-ticketless multi-content dumps not work. Do they fail hash checks or what errors are you getting when trying to compress them?

**Comment by ElektroStudios** [comment]
> Why do some non-ticketless multi-content dumps not work. Do they fail hash checks or what errors are you getting when trying to compress them?

At the end of this comment is the output generated when attempting to compress a multi-content NSP file containing tickets.

The output is filled with "could not find title key" messages although I have all the necessary keys for each DLC and update saved in the titlekeys.txt file. Additionally, the SolidCompressor.py class fails with the error message: "TypeError: can't concat NoneType to bytes" when attempting to concatenate data to the header.

Since I lack the advanced knowledge about these Nintendo Switch-related things that someone like you might have, I don’t think it’s worthwhile for me to delve deeper into the code to bypass certain checks or validations to try fix this issue.

For now, I find it safer to simply use NSZ with ticketless multi-content files to avoid complications. Over the past few days, I’ve compressed more than 300 different ticketless multi-content NSP roms without any issues. I’ve also decompressed and tested many of them on a PC emulator to confirm that they boot properly.

```
Compressing "C:\Games\Nintendo Switch\Tools\NSZ\_Para Comprimir\Dungeons 3 [010058C017024000] [v65536] (1G+1U+4D).nsp"...


             NSZ v4.6   ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'

[OPEN  ]     5424f3270d1d920de239128699a6d534.cnmt.xml 0x5ab bytes at 0x184991901
[OPEN  ]     5424f3270d1d920de239128699a6d534.cnmt.nca 0xe00 bytes at 0x184990b01
[OPEN  ]     ba77f4b75abf2fa6be56d9577e21f7e0.nca 0x2a000 bytes at 0x184966b01
[OPEN  ]     ab81ca2395d805e72cf2ce610e0e68d8.nca 0x5d400 bytes at 0x184909701
[OPEN  ]     1a5f38744ed2855741fe06cd148c1ab0.nca 0x178378000 bytes at 0xc591701
[OPEN  ]     010058c017025004000000000000000d.cert 0x700 bytes at 0xc591001
[OPEN  ]     010058c017025004000000000000000d.tik 0x2c0 bytes at 0xc590d41
[OPEN  ]     62706aaf68e11a14148139577d1af455.cnmt.xml 0x3a6 bytes at 0xc59099b
[OPEN  ]     62706aaf68e11a14148139577d1af455.cnmt.nca 0xe00 bytes at 0xc58fb9b
[OPEN  ]     fe25d0f23d769f8f1a9c603938a4ac61.nca 0x1c000 bytes at 0xc573b9b
[OPEN  ]     010058c017025003000000000000000d.cert 0x700 bytes at 0xc57349b
[OPEN  ]     010058c017025003000000000000000d.tik 0x2c0 bytes at 0xc5731db
[OPEN  ]     aee1b67ec46773275bdec32aaa948d0f.cnmt.xml 0x3a6 bytes at 0xc572e35
[OPEN  ]     aee1b67ec46773275bdec32aaa948d0f.cnmt.nca 0xe00 bytes at 0xc572035
[OPEN  ]     6abf140d5da935a1926df2741a6d1d9f.nca 0x1c000 bytes at 0xc556035
[OPEN  ]     010058c017025002000000000000000d.cert 0x700 bytes at 0xc555935
[OPEN  ]     010058c017025002000000000000000d.tik 0x2c0 bytes at 0xc555675
[OPEN  ]     bbb26e27cfcdf8a314f66d9c5ab1f93b.cnmt.xml 0x3a6 bytes at 0xc5552cf
[OPEN  ]     bbb26e27cfcdf8a314f66d9c5ab1f93b.cnmt.nca 0xe00 bytes at 0xc5544cf
[OPEN  ]     da00ceb24d1eaff0e00456d8f0053aac.nca 0x1c000 bytes at 0xc5384cf
[OPEN  ]     010058c017025001000000000000000d.cert 0x700 bytes at 0xc537dcf
[OPEN  ]     010058c017025001000000000000000d.tik 0x2c0 bytes at 0xc537b0f
[OPEN  ]     87d8daf81dce2ee57b395595ff7361c0.cnmt.xml 0x3a6 bytes at 0xc537769
[OPEN  ]     87d8daf81dce2ee57b395595ff7361c0.cnmt.nca 0xe00 bytes at 0xc536969
[OPEN  ]     137df22f26e5b9e6622cf37be9c76350.nca 0x1c000 bytes at 0xc51a969
[OPEN  ]     010058c0170248000000000000000010.cert 0x700 bytes at 0xc51a269
[OPEN  ]     010058c0170248000000000000000010.tik 0x2c0 bytes at 0xc519fa9
[OPEN  ]     68bf0bee0b46ea19d1bde2221d002273.cnmt.xml 0x5a9 bytes at 0xc519a00
[OPEN  ]     68bf0bee0b46ea19d1bde2221d002273.cnmt.nca 0x1000 bytes at 0xc518a00
[OPEN  ]     a8fd97c85c66e7139766baaa57f71300.nca 0x2a200 bytes at 0xc4ee800
[OPEN  ]     78beaa74f71a05ed4ba9e08211240e8d.nca 0x5d400 bytes at 0xc491400
[OPEN  ]     485b72f3f7bc69f27db1be36c2bf31a7.nca 0xc491400 bytes at 0x0
[OPEN  ]     Application_010058c017024000.cnmt 0xf8 bytes at 0x0
[OPEN  ]     Application_010058c017024000.cnmt 0xf8 bytes at 0x0
[OPEN  ]     subsdk0 0x33a851 bytes at 0x2cb30eb
[OPEN  ]     sdk 0x5b64af bytes at 0x26fcc3c
[OPEN  ]     rtld 0x1bdc bytes at 0x26fb060
[OPEN  ]     main.npdm 0x624 bytes at 0x26faa3c
[OPEN  ]     main 0x26faa3c bytes at 0x0
[OPEN  ]     subsdk0 0x33a851 bytes at 0x2cb30eb
[OPEN  ]     sdk 0x5b64af bytes at 0x26fcc3c
[OPEN  ]     rtld 0x1bdc bytes at 0x26fb060
[OPEN  ]     main.npdm 0x624 bytes at 0x26faa3c
[OPEN  ]     main 0x26faa3c bytes at 0x0
[OPEN  ]     StartupMovie.gif 0xc74b bytes at 0x5009
[OPEN  ]     NintendoLogo.png 0x5009 bytes at 0x0
[OPEN  ]     StartupMovie.gif 0xc74b bytes at 0x5009
[OPEN  ]     NintendoLogo.png 0x5009 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025004.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025004.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025003.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025003.cnmt 0x88 bytes at 0x0
could not find title key 010058C017025003!
[OPEN  ]     AddOnContent_010058c017025002.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025002.cnmt 0x88 bytes at 0x0
could not find title key 010058C017025002!
[OPEN  ]     AddOnContent_010058c017025001.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025001.cnmt 0x88 bytes at 0x0
could not find title key 010058C017025001!
[OPEN  ]     Patch_010058c017024800.cnmt 0x1b4 bytes at 0x0
[OPEN  ]     Patch_010058c017024800.cnmt 0x1b4 bytes at 0x0
could not find title key 010058C017024800!
Skipped already existing 010058c0170248000000000000000010

titlekeys.txt:
010058c0170248000000000000000010|............CENSORED............|Dungeons 3 - Nintendo Switch Edition [010058C017024800][v65536][US]
010058c017025001000000000000000d|............CENSORED............|Dungeons 3 [DLC A Multitude of Maps] [010058C017025001][v0][US]
010058c017025002000000000000000d|............CENSORED............|Dungeons 3 [DLC An Unexpected] [010058C017025002][v0][US]
010058c017025003000000000000000d|............CENSORED............|Dungeons 3 [DLC Clash of Gods] [010058C017025003][v0][US]
010058c017025004000000000000000d|............CENSORED............|Dungeons 3 [DLC Famous Last Words] [010058C017025004][v0][US]
[OPEN  ]     5424f3270d1d920de239128699a6d534.cnmt.xml 0x5ab bytes at 0x184991901
[OPEN  ]     5424f3270d1d920de239128699a6d534.cnmt.nca 0xe00 bytes at 0x184990b01
[OPEN  ]     ba77f4b75abf2fa6be56d9577e21f7e0.nca 0x2a000 bytes at 0x184966b01
[OPEN  ]     ab81ca2395d805e72cf2ce610e0e68d8.nca 0x5d400 bytes at 0x184909701
[OPEN  ]     1a5f38744ed2855741fe06cd148c1ab0.nca 0x178378000 bytes at 0xc591701
[OPEN  ]     010058c017025004000000000000000d.cert 0x700 bytes at 0xc591001
[OPEN  ]     010058c017025004000000000000000d.tik 0x2c0 bytes at 0xc590d41
[OPEN  ]     62706aaf68e11a14148139577d1af455.cnmt.xml 0x3a6 bytes at 0xc59099b
[OPEN  ]     62706aaf68e11a14148139577d1af455.cnmt.nca 0xe00 bytes at 0xc58fb9b
[OPEN  ]     fe25d0f23d769f8f1a9c603938a4ac61.nca 0x1c000 bytes at 0xc573b9b
[OPEN  ]     010058c017025003000000000000000d.cert 0x700 bytes at 0xc57349b
[OPEN  ]     010058c017025003000000000000000d.tik 0x2c0 bytes at 0xc5731db
[OPEN  ]     aee1b67ec46773275bdec32aaa948d0f.cnmt.xml 0x3a6 bytes at 0xc572e35
[OPEN  ]     aee1b67ec46773275bdec32aaa948d0f.cnmt.nca 0xe00 bytes at 0xc572035
[OPEN  ]     6abf140d5da935a1926df2741a6d1d9f.nca 0x1c000 bytes at 0xc556035
[OPEN  ]     010058c017025002000000000000000d.cert 0x700 bytes at 0xc555935
[OPEN  ]     010058c017025002000000000000000d.tik 0x2c0 bytes at 0xc555675
[OPEN  ]     bbb26e27cfcdf8a314f66d9c5ab1f93b.cnmt.xml 0x3a6 bytes at 0xc5552cf
[OPEN  ]     bbb26e27cfcdf8a314f66d9c5ab1f93b.cnmt.nca 0xe00 bytes at 0xc5544cf
[OPEN  ]     da00ceb24d1eaff0e00456d8f0053aac.nca 0x1c000 bytes at 0xc5384cf
[OPEN  ]     010058c017025001000000000000000d.cert 0x700 bytes at 0xc537dcf
[OPEN  ]     010058c017025001000000000000000d.tik 0x2c0 bytes at 0xc537b0f
[OPEN  ]     87d8daf81dce2ee57b395595ff7361c0.cnmt.xml 0x3a6 bytes at 0xc537769
[OPEN  ]     87d8daf81dce2ee57b395595ff7361c0.cnmt.nca 0xe00 bytes at 0xc536969
[OPEN  ]     137df22f26e5b9e6622cf37be9c76350.nca 0x1c000 bytes at 0xc51a969
[OPEN  ]     010058c0170248000000000000000010.cert 0x700 bytes at 0xc51a269
[OPEN  ]     010058c0170248000000000000000010.tik 0x2c0 bytes at 0xc519fa9
[OPEN  ]     68bf0bee0b46ea19d1bde2221d002273.cnmt.xml 0x5a9 bytes at 0xc519a00
[OPEN  ]     68bf0bee0b46ea19d1bde2221d002273.cnmt.nca 0x1000 bytes at 0xc518a00
[OPEN  ]     a8fd97c85c66e7139766baaa57f71300.nca 0x2a200 bytes at 0xc4ee800
[OPEN  ]     78beaa74f71a05ed4ba9e08211240e8d.nca 0x5d400 bytes at 0xc491400
[OPEN  ]     485b72f3f7bc69f27db1be36c2bf31a7.nca 0xc491400 bytes at 0x0
[OPEN  ]     Application_010058c017024000.cnmt 0xf8 bytes at 0x0
[OPEN  ]     Application_010058c017024000.cnmt 0xf8 bytes at 0x0
[OPEN  ]     subsdk0 0x33a851 bytes at 0x2cb30eb
[OPEN  ]     sdk 0x5b64af bytes at 0x26fcc3c
[OPEN  ]     rtld 0x1bdc bytes at 0x26fb060
[OPEN  ]     main.npdm 0x624 bytes at 0x26faa3c
[OPEN  ]     main 0x26faa3c bytes at 0x0
[OPEN  ]     subsdk0 0x33a851 bytes at 0x2cb30eb
[OPEN  ]     sdk 0x5b64af bytes at 0x26fcc3c
[OPEN  ]     rtld 0x1bdc bytes at 0x26fb060
[OPEN  ]     main.npdm 0x624 bytes at 0x26faa3c
[OPEN  ]     main 0x26faa3c bytes at 0x0
[OPEN  ]     StartupMovie.gif 0xc74b bytes at 0x5009
[OPEN  ]     NintendoLogo.png 0x5009 bytes at 0x0
[OPEN  ]     StartupMovie.gif 0xc74b bytes at 0x5009
[OPEN  ]     NintendoLogo.png 0x5009 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025004.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025004.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025003.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025003.cnmt 0x88 bytes at 0x0
could not find title key 010058C017025003!
[OPEN  ]     AddOnContent_010058c017025002.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025002.cnmt 0x88 bytes at 0x0
could not find title key 010058C017025002!
[OPEN  ]     AddOnContent_010058c017025001.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025001.cnmt 0x88 bytes at 0x0
could not find title key 010058C017025001!
[OPEN  ]     Patch_010058c017024800.cnmt 0x1b4 bytes at 0x0
[OPEN  ]     Patch_010058c017024800.cnmt 0x1b4 bytes at 0x0
could not find title key 010058C017024800!
[OPEN  ]     5424f3270d1d920de239128699a6d534.cnmt.xml 0x5ab bytes at 0x184991901
[OPEN  ]     5424f3270d1d920de239128699a6d534.cnmt.nca 0xe00 bytes at 0x184990b01
[OPEN  ]     ba77f4b75abf2fa6be56d9577e21f7e0.nca 0x2a000 bytes at 0x184966b01
[OPEN  ]     ab81ca2395d805e72cf2ce610e0e68d8.nca 0x5d400 bytes at 0x184909701
[OPEN  ]     1a5f38744ed2855741fe06cd148c1ab0.nca 0x178378000 bytes at 0xc591701
[OPEN  ]     010058c017025004000000000000000d.cert 0x700 bytes at 0xc591001
[OPEN  ]     010058c017025004000000000000000d.tik 0x2c0 bytes at 0xc590d41
[OPEN  ]     62706aaf68e11a14148139577d1af455.cnmt.xml 0x3a6 bytes at 0xc59099b
[OPEN  ]     62706aaf68e11a14148139577d1af455.cnmt.nca 0xe00 bytes at 0xc58fb9b
[OPEN  ]     fe25d0f23d769f8f1a9c603938a4ac61.nca 0x1c000 bytes at 0xc573b9b
[OPEN  ]     010058c017025003000000000000000d.cert 0x700 bytes at 0xc57349b
[OPEN  ]     010058c017025003000000000000000d.tik 0x2c0 bytes at 0xc5731db
[OPEN  ]     aee1b67ec46773275bdec32aaa948d0f.cnmt.xml 0x3a6 bytes at 0xc572e35
[OPEN  ]     aee1b67ec46773275bdec32aaa948d0f.cnmt.nca 0xe00 bytes at 0xc572035
[OPEN  ]     6abf140d5da935a1926df2741a6d1d9f.nca 0x1c000 bytes at 0xc556035
[OPEN  ]     010058c017025002000000000000000d.cert 0x700 bytes at 0xc555935
[OPEN  ]     010058c017025002000000000000000d.tik 0x2c0 bytes at 0xc555675
[OPEN  ]     bbb26e27cfcdf8a314f66d9c5ab1f93b.cnmt.xml 0x3a6 bytes at 0xc5552cf
[OPEN  ]     bbb26e27cfcdf8a314f66d9c5ab1f93b.cnmt.nca 0xe00 bytes at 0xc5544cf
[OPEN  ]     da00ceb24d1eaff0e00456d8f0053aac.nca 0x1c000 bytes at 0xc5384cf
[OPEN  ]     010058c017025001000000000000000d.cert 0x700 bytes at 0xc537dcf
[OPEN  ]     010058c017025001000000000000000d.tik 0x2c0 bytes at 0xc537b0f
[OPEN  ]     87d8daf81dce2ee57b395595ff7361c0.cnmt.xml 0x3a6 bytes at 0xc537769
[OPEN  ]     87d8daf81dce2ee57b395595ff7361c0.cnmt.nca 0xe00 bytes at 0xc536969
[OPEN  ]     137df22f26e5b9e6622cf37be9c76350.nca 0x1c000 bytes at 0xc51a969
[OPEN  ]     010058c0170248000000000000000010.cert 0x700 bytes at 0xc51a269
[OPEN  ]     010058c0170248000000000000000010.tik 0x2c0 bytes at 0xc519fa9
[OPEN  ]     68bf0bee0b46ea19d1bde2221d002273.cnmt.xml 0x5a9 bytes at 0xc519a00
[OPEN  ]     68bf0bee0b46ea19d1bde2221d002273.cnmt.nca 0x1000 bytes at 0xc518a00
[OPEN  ]     a8fd97c85c66e7139766baaa57f71300.nca 0x2a200 bytes at 0xc4ee800
[OPEN  ]     78beaa74f71a05ed4ba9e08211240e8d.nca 0x5d400 bytes at 0xc491400
[OPEN  ]     485b72f3f7bc69f27db1be36c2bf31a7.nca 0xc491400 bytes at 0x0
[OPEN  ]     Application_010058c017024000.cnmt 0xf8 bytes at 0x0
[OPEN  ]     Application_010058c017024000.cnmt 0xf8 bytes at 0x0
[OPEN  ]     subsdk0 0x33a851 bytes at 0x2cb30eb
[OPEN  ]     sdk 0x5b64af bytes at 0x26fcc3c
[OPEN  ]     rtld 0x1bdc bytes at 0x26fb060
[OPEN  ]     main.npdm 0x624 bytes at 0x26faa3c
[OPEN  ]     main 0x26faa3c bytes at 0x0
[OPEN  ]     subsdk0 0x33a851 bytes at 0x2cb30eb
[OPEN  ]     sdk 0x5b64af bytes at 0x26fcc3c
[OPEN  ]     rtld 0x1bdc bytes at 0x26fb060
[OPEN  ]     main.npdm 0x624 bytes at 0x26faa3c
[OPEN  ]     main 0x26faa3c bytes at 0x0
[OPEN  ]     StartupMovie.gif 0xc74b bytes at 0x5009
[OPEN  ]     NintendoLogo.png 0x5009 bytes at 0x0
[OPEN  ]     StartupMovie.gif 0xc74b bytes at 0x5009
[OPEN  ]     NintendoLogo.png 0x5009 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025004.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025004.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025003.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025003.cnmt 0x88 bytes at 0x0
could not find title key 010058C017025003!
[OPEN  ]     AddOnContent_010058c017025002.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025002.cnmt 0x88 bytes at 0x0
could not find title key 010058C017025002!
[OPEN  ]     AddOnContent_010058c017025001.cnmt 0x88 bytes at 0x0
[OPEN  ]     AddOnContent_010058c017025001.cnmt 0x88 bytes at 0x0
could not find title key 010058C017025001!
[OPEN  ]     Patch_010058c017024800.cnmt 0x1b4 bytes at 0x0
[OPEN  ]     Patch_010058c017024800.cnmt 0x1b4 bytes at 0x0
could not find title key 010058C017024800!
Solid compressing (level 22 ldm) C:\Games\Nintendo Switch\Tools\NSZ\_Para Comprimir\Dungeons 3 [010058C017024000] [v65536] (1G+1U+4D).nsp -> C:\Games\Nintendo Switch\Tools\NSZ\_ya comprimidos\Dungeons 3 [010058C017024000] [v65536] (1G+1U+4D).nsz
[ADDING]     485b72f3f7bc69f27db1be36c2bf31a7.ncz 0xc491400 bytes to PFS0 at 0x800
Traceback (most recent call last):
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\site-packages\nsz\SolidCompressor.py", line 133, in solidCompressNsp
    processContainer(container, nsp, compressionLevel, keep, useLongDistanceMode, threads, statusReport, id, pleaseNoPrint)
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\site-packages\nsz\SolidCompressor.py", line 55, in processContainer
    header += fs.cryptoKey
TypeError: can't concat NoneType to bytes

[VERIFY NSZ] C:\Games\Nintendo Switch\Tools\NSZ\_ya comprimidos\Dungeons 3 [010058C017024000] [v65536] (1G+1U+4D).nsz
nut exception: [Errno 2] No such file or directory: 'C:\\Games\\Nintendo Switch\\Tools\\NSZ\\_ya comprimidos\\Dungeons 3 [010058C017024000] [v65536] (1G+1U+4D).nsz'
Process Process-2:
Traceback (most recent call last):
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\site-packages\nsz\__init__.py", line 51, in solidCompressTask
    verify(outFile, fixPadding, True, keep, None if quickVerify else filePath, [statusReport, id], pleaseNoPrint)
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\site-packages\nsz\__init__.py", line 91, in verify
    NszVerify(filePath, fixPadding, raiseVerificationException, raisePfs0Exception, originalFilePath, statusReportInfo, pleaseNoPrint)
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\site-packages\nsz\NszDecompressor.py", line 46, in verify
    __decompressNsz(filePath, None, fixPadding, False, raiseVerificationException, raisePfs0Exception, originalFilePath, statusReportInfo, pleaseNoPrint)
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\site-packages\nsz\NszDecompressor.py", line 223, in __decompressNsz
    container.open(str(filePath), 'rb')
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\site-packages\nsz\Fs\Nsp.py", line 198, in open
    super(Nsp, self).open(path or self.path, mode, cryptoType, cryptoKey, cryptoCounter)
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\site-packages\nsz\Fs\Pfs0.py", line 228, in open
    r = super(Pfs0, self).open(path, mode, cryptoType, cryptoKey, cryptoCounter)
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\site-packages\nsz\Fs\BaseFs.py", line 97, in open
    r = super(BaseFs, self).open(path, mode, cryptoType, cryptoKey, cryptoCounter)
  File "C:\Games\Nintendo Switch\Tools\NSZ\lib\site-packages\nsz\Fs\File.py", line 210, in open
    self.f = open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Games\\Nintendo Switch\\Tools\\NSZ\\_ya comprimidos\\Dungeons 3 [010058C017024000] [v65536] (1G+1U+4D).nsz'

Compressing   0%|                                                                    |   0/100 MiB [00:07<?, 0.00 MiB/s]
```

**Comment by ElektroStudios** [comment]
>     * NSZ supports processing multiple files simultaneously. By default, 4 files are processed simultaneously. Global variables in python are static meaning every instance of Ticket will share the same global isTicketless state. This should cause issues if the user mixes non-ticketless with ticketless files as they will keep overwriting each other’s isTicketless state. The only reason this works is probably because global variables are not shared between multiple processes and NSZ is using multiprocessing to process multiple files at once.

You are absolutely right, thank you for pointing out my mistake.

All this time I was calling nsz.exe passing to it a full file path instead of a directory path, so I didn't notice the multi-file processing feature because it was only processing one file at a time.

-----------

To try to solve this problem I first thought of using a dictionary with key: The full path of each NSP file to be processed, and value: A boolean flag indicating if the NSP is ticketless.

But after several hours and due to my limited knowledge of Python it was impossible for me to find the way and the class where to declare this object to ensure that it is only instantiated once during the lifetime of the process, and to be able to access said object in the other classes where it would be necessary to check the dictionary.

Luckily I was able to come up with another approach which seems to work as expected and should be just as efficient, if not more so, than using a dictionary. The solution is to remove the global variable `isTicketless` and instead create a `ticketless` attribute on the instance of the `Nsp` class, and check that attribute when required. Everything seems fine for me using this approach.

Finally, here I attach the output of nsz.exe working in multi-file processing mode, where a ticketless multicontent NSP file containing the base game with one update (whose identifiers in the output are 4c238f052e4c7256ad5e930dd936556a.ncz and e3fa00d2e2801cffc206a52f2c7ad823.ncz) and two normal NSP files (only base game, with tickets) are processed.

[nsz output.txt](https://github.com/user-attachments/files/18241057/nsz.output.txt)

I'm almost done with this solution, but I require some more time to test compressing a bunch of files and then committing the changes that I've talked about.

**Comment by ElektroStudios** [comment]
# [Improved ticketless handling when multi-file processing](https://github.com/nicoboss/nsz/pull/196/commits/877ebbaf85af40e20e9047405a6782d1fb1de861)

With this commit, all my previous changes to the 'Ticket.py' and '__init__.py' files have been completelly reverted because they are not required anymore. My apologies for the slight mess. 

The only files with actual changes after this commit now are `Nsp.py` and `NszDecompressor.py`, and they are very small changes (one single line in file `Nsp.py` to set the ticketless attribute, and the addition of two conditional blocks in `NszDecompressor.py` to handle the presence of that ticketless attribute on hash verification in order to avoid exception `VerificationException`), so I am sure you will feel satisfied with these changes as now are less and simplified compared than in the previous two commits, and it still does / fixes the same issue(s).

**Review by nicoboss — APPROVED** [review]

**Comment by nicoboss** [comment]
> The output is filled with "could not find title key" messages although I have all the necessary keys for each DLC and update saved in the titlekeys.txt file. Additionally, the SolidCompressor.py class fails with the error message: "TypeError: can't concat NoneType to bytes" when attempting to concatenate data to the header. Since I lack the advanced knowledge about these Nintendo Switch-related things that someone like you might have, I don’t think it’s worthwhile for me to delve deeper into the code to bypass certain checks or validations to try fix this issue.

Thanks a lot for posting the output. This will help me to investigate and fix this issue. No worries I didn’t expect you to look into it but was just curios what causes it to fail.

> For now, I find it safer to simply use NSZ with ticketless multi-content files to avoid complications. Over the past few days, I’ve compressed more than 300 different ticketless multi-content NSP roms without any issues. I’ve also decompressed and tested many of them on a emulator for PC to confirm that they boot properly.

Big thanks for the massive amount of testing you performed! That is way more than I did to test your changes and makes me quite confident that there are no edge-cases we missed.

> You are absolutely right, thank you for pointing out my mistake.

Thanks to multiprocessing not sharding global variables it mainly was really confusing design but I wanted it fixed because this would likely have caused issues for 3rd party software depending on NSZ. Thanks a lot for fixing it!

> All this time I was calling nsz.exe passing to it a full file path instead of a directory path, so I didn't notice the multi-file processing feature because it was only processing one file at a time.

I recommend to make use of the multi-file feature as it should allow you to fully utilize your CPU but I have to say the zstandard internal multithreading improved a lot in the past year so this might no longer make as much of a performance difference as it used to.

> Luckily I was able to come up with another approach which seems to work as expected and should be just as efficient, if not more so, than using a dictionary. The solution is to remove the global variable isTicketless and instead create a ticketless attribute on the instance of the Nsp class, and check that attribute when required. Everything seems fine for me using this approach.

Thanks a lot for the huge effort you put into improving your previous implementation. I highly appreciate it. I really like your approach of defining an `ticketless` attribute. This for sure is a much cleaner way of implementing this that will work no matter how processing multiple files at once is implemented.

**Pull request merged**
