### PR TITLE
fix issue 79 + 80

### PR DESCRIPTION
**Pull request by gabest11**

### CODE REVIEW

**Comment by gabest11** [comment]
Oh, I smuggled in the level 0 compression option too. That's what I use to store compress and 7zip it to make it even less big.

**Comment by gabest11** [comment]
During my adventures I noticed that verification does a lot of extra reads. Like 17 times as many. self.Position is incremented slowly, less then the block size, and this makes BlockDecompressorReader.read decompress the block every single time. The last block should be cached.

**Comment by nicoboss** [comment]
Thanks a lot for finding and fixing booth issues!

Because the last block is most likely smaller when compressed then the actual block size the issue #79 went undetected over all this time. The only reason you encountered it, is because of you setting all blocks to be uncompressible. I really like your fix of always compressing it as that way we don't break backwards compatibility and it's also the easiest way of implementing this edge case.

Great you found that race condition you described in #80. I don't think I ever encountered it on my PC but definitely could explain some of the wired issues other had with BlockCompression. It probably also stayed undetected because of block compression being way less popular then solid compression due to it only being the default for compressing XCI and not NSP files.

I like your idea of introducing compressionLevel == 0 to block compression. That way custom compression algorithms like 7zip are possible without breaking any compatibility. Great decision for not using SolidCompression for that. I have never thought of using nsz as a format to store decrypted ROMs only to compress it with a different software but makes totally sense. Definitely will try it out by compressing one as Solid LZMA2 Ultra 7zip with 1536 MB Dictionary and 273 word size.

Awesome you noticed the decompression work being done multiple times! Thanks to your block read cache The Test NSZ block decompression testcase went from taking 20 seconds to taking 7 seconds which is absolutely huge especially because it also saves time during verifying as decompressing is part of it. In total this change put the Azure pipeline form 7m 22s to 5m 15s which is huge if you keep in mind that half of the time is spent for solid compression which is totally unaffected by this change.

Thanks for your huge contribution to this project – it’s highly appreciated.

**Comment by gabest11** [comment]
Wait, I just noticed that the last block issue was not fully fixed (79). If you use compression level >= 1, it can still a problem. 

The worker thread should know when it gets the last block to act correctly, it just knows the block offset now.

Anyways, after processing 170 games (I’m converting all my old nspz from last year to nsz), none of them has failed the verification. I use level 0, but the last block is still going through the compression path if it is less than the block size, so in theory it should run into this problem. 

The race condition was much worse, it started happening before completing the first ten games. It makes sense for the while loop to go around faster than the worker thread to activate. Only saw it happening with one item, maybe adding a second already triggers the first job in the queue.

7zip on max settings is about 3/4 of nsz’s solid mode. Means about a terabyte less on my NAS. Yea, I have a hoarding problem.

I hope the reader returns the copy of the cached block, as it must not be modified by the outer caller, the data has to stay the same for sequential calls. Don’t know python enough to tell. I think the [:] operator on the buffer returns a copy, so it’s good.

**Comment by gabest11** [comment]
Hey, it’s me again. Did you get my reply yesterday? It went to a strange reply address at github, and I sent it from my personal email address to which my github address is forwarded to.

I just wanted to ask how do you test the decompression speed. Does it write the progress to the console? I ran it through visual studio profiler and 60% of the time is spent on updating the bar. If I add an incrementing counter and update the progress every Nth time, like if (counter&255) == 0, the speed jumps from 40MB/s to 120MB/s, even when compressed.

**Comment by nicoboss** [comment]
>Wait, I just noticed that the last block issue was not fully fixed (79). If you use compression level >= 1, it can still a problem.

Ah yes true. Misread that. Reopened #79 and will fix it probably tomorrow by my self – only requires adding a compressionLevel > 0 and len(buffer) < blockSize condition that always compresses it if smaller the blockSize. But then there’s the issue that this would allow compressed blocks to be larger than uncompressed data which violates fundamental file format specifications. Honestly I guess best would be best to never compress the last block but that would cause compatibility issues. Have to think about that. Anyways thanks for pointing that out because it’s not something I could test as no game is affected by this issue as far I’m aware.
<br>
>Anyways, after processing 170 games (I’m converting all my old nspz from last year to nsz), none of them has failed the verification. I use level 0, but the last block is still going through the compression path if it is less than the block size, so in theory it should run into this problem.

Now I remember you from nsZit. Already thought your name sounds familiar. Feel so bad you have to switch to nsz now. nsZip was just too complicated for the homebrew community to implement which kind of forced me to settle for a less complex file format.
<br>
>7zip on max settings is about 3/4 of nsz’s solid mode. Means about a terabyte less on my NAS. Yea, I have a hoarding problem.

LZMA is awesome. The only reason zStandard is used is because of its much faster decompression speed and extremely low decompression RAM usage (needed if ever implemented as sysmodule) which especially is relevant when decompressing games directly on real hardware using homebrew. It turned out it’s faster to Networks transfer over the compressed file while on the fly decompressing it while installing the transferring the uncompressed file which made a lot of Homebrew using the nsz file format.
<br>
>I hope the reader returns the copy of the cached block, as it must not be modified by the outer caller, the data has to stay the same for sequential calls. Don’t know python enough to tell. I think the [:] operator on the buffer returns a copy, so it’s good.

Yes seems to do exactly what it’s supposed to do as it gave an absolute huge performance improvement
<br>
>Hey, it’s me again. Did you get my reply yesterday? It went to a strange reply address at github, and I sent it from my personal email address to which my github address is forwarded to.

Yes I saw it perfectly fine. Sorry cannot always answer immediately is I’m usually quite busy so always give me a few days.
<br>
>I just wanted to ask how do you test the decompression speed. Does it write the progress to the console? I ran it through visual studio profiler and 60% of the time is spent on updating the bar. If I add an incrementing counter and update the progress every Nth time, like if (counter&255) == 0, the speed jumps from 40MB/s to 120MB/s, even when compressed.

Yes, the progress bar is written to the console. In versions prior to 3.0 a more lightweight library was used but because of simultaneously tasks requiring simultaneous progress bars I had to switch to the enlightened library from https://github.com/Rockhopper-Technologies/enlighten. Honestly never benchmarked it as I just expected such a popular library to perform well despite me probably updating the status bar way to often so you could be right. To test decompression speed, I usually just take a look at the decompression speed printed to the console and how long the azure pipeline takes for certain test folders to decompress. It could also be that your change just manipulated the actual speed calculation. To be sure just make a pull request and compare the results of the azure tests with master and see if there is a real performance improvement. If not just close the Pull Request. Definitely will look into that after the 3.2 release which I should do as soon as possible.

**Pull request merged**
